language: node_js
cache:
  directories:
  - node_modules
sudo: required
dist: trusty
node_js: '8'
env: CXX=g++-4.8
addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages: g++-4.8 libnotify-bin
before_script: npm install -g gulp
script:
- gulp prep
before_deploy:
- mkdir deploy
- gulp travisZip
deploy:
  provider: releases
  api_key:
    secure: kravLuO8x9ITp3bD/TSr89HX5530NPFi8+cq5uL0Q24s2zj+QW2RQFWmQWljJSre+z7D1WTtu/HuiPK1aJ7pjrEkl3E8kf1oi4HdZIMaNKeKXWqeIDYfwKHM+25oXAAEZSyw7FuLgBDjPBhKrFLuFGoSUXqBuap/77FbPqXdBk2cHLz0vmYTskFw7SLOiXW4Cqz+DyfvuB2nDKtvYQ58DZSrv1posVCxjWTW5abCa+uJFpqsyLGVs0GrSN93xWgLQi2sNkF5s2PPIdjp0aVJ+PIkd5x9otYrGjlD8Z7JnyOFbtH/ZDgCfxuTTJmn0s2I58dI5uLNgOgtp119TtiVjCsvW1HN3yIoVhsTRsRhsQJF5KPM76rIPnlyuUyi1FK1RmPH0RxPM5vt0zOXdfPDAeRP3+5MmETrxpm9wRCRVEO31tCMY+JGPhZD0opdALS3l4++z5WFwo1hxnpd1tfixzitBl9LgUaAzO8jYW4oeomnlPfQkmPH2GwJuY2RfHQsqv8TZh2uz4qxEgDN+F5Bc4ILS0QRhSIhwszdMY51xXuOyppdi4JVVmSlaLxVwgXUepJOTds7UDBTNFUK3Sjg+ubG382shh9CF5ulxKU3u6epOA/TDzGq7pWFK0kkXmhbYJpMMbWnsf7PNBvF5mMAxwZJKZ0uCjcloRlEvAy3ro8=
  file_glob: true
  file: deploy/*
  skip_cleanup: true
  on:
    repo: east-coin/eastwallet
    branch: master
    tags: true
